# The endpoint the service listens on 
service_endpoint: "https://assisted-service-open-cluster-management.apps.jetlag-ibm0.performance-scale.cloud"

# A public key. This doesn't make any difference, you can leave it as is
ssh_pub_key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLK6KYdjOHpuDxS6wFG8ts/7X6nPTHHfsXxN34PGY/HCEAwHSgw6ShWIwcqueGfR9kgPGdClWZrX25MdnF3d+6Y= swarm@swarm"

# A path to the file containing your pull secret, you can get yours from https://cloud.redhat.com/openshift/install/pull-secret
pull_secret_file: "/home/omer/omer-ps"

# Swarm cluster release image
release_image: "quay.io/openshift-release-dev/ocp-release:4.9.7-x86_64"